#!/bin/bash
#
# Copyright 2017-2018 Gaël PORTAY <gael.portay@gmail.com>
#
# Licensed under the MIT license.
#

set -e

DATADIR="${DATADIR:-$PWD}"

tmpdir="$(mktemp -d "${TMPDIR:-/tmp}/${0##*/}-XXXXXX")"
trap 'rm -Rf "$tmpdir"' 0

maketest_flags=( "O=$tmpdir/" "-I$DATADIR" "-f$DATADIR/Maketest" "--no-print-directory" )
MAKETEST="$0"
MTFLAGS="${maketest_flags[*]}"
export MAKETEST MTFLAGS
export DATADIR

exec make "${maketest_flags[@]}" "$@"
